/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.ts"],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        "bone-light": {
          primary: "#155e75",
          "primary-content": "#ffffff",
          secondary: "#52606d",
          "secondary-content": "#ffffff",
          accent: "#3b82f6",
          "accent-content": "#ffffff",
          neutral: "#334e68",
          "neutral-content": "#f0f4f8",
          "base-100": "#f5f0e8",
          "base-200": "#ede6d8",
          "base-300": "#e5dcc8",
          "base-content": "#1a1a1a",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#22c55e",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-content": "#ffffff",
        },
      },
      {
        "pure-dark": {
          primary: "#3b82f6",
          "primary-content": "#ffffff",
          secondary: "#64748b",
          "secondary-content": "#ffffff",
          accent: "#60a5fa",
          "accent-content": "#000000",
          neutral: "#1e293b",
          "neutral-content": "#e2e8f0",
          "base-100": "#000000",
          "base-200": "#0a0a0a",
          "base-300": "#141414",
          "base-content": "#e8e8e8",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#22c55e",
          "success-content": "#000000",
          warning: "#f59e0b",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-content": "#000000",
        },
      },
    ],
  },
};
