const BSRS_DD_FIELD_MAP: Record<string, string> = {
  case_id: "CASE",
  bcv_rec_id: "BCV_REC_ID",
  retstat: "RETSTAT",
  id: "ID",
  fname: "FNAME",
  lname: "LNAME",
  sfname: "SFNAME",
  slname: "SLNAME",
  relation: "RELATION",
  psex: "PSEX",
  ssex: "SSEX",
  mstat: "MSTAT",
  dob: "DOB",
  sdob: "SDOB",
  dod: "DOD",
  non_spouse_benf: "NON_SPOUSE_BENF",
  doh: "DOH",
  dop: "DOP",
  dote: "DOTE",
  dor: "DOR",
  sbcd: "SBCD",
  nrd: "NRD",
  erd: "ERD",
  eurd: "EURD",
  xra: "XRA",
  xrd: "XRD",
  sxra: "SXRA",
  calc_indicator: "CALC_INDICATOR",
  form_code_nsf: "FORM_CODE_NSF",
  form_code_nmf: "FORM_CODE_NMF",
  form_code_ptp: "FORM_CODE_PTP",
  form_code_ptp_qpsa: "FORM_CODE_PTP_QPSA",
  form_code_death: "FORM_CODE_DEATH",
  form_code_ard: "FORM_CODE_ARD",
  spc_ard: "SPC_ARD",
  mths_ard: "MTHS_ARD",
  lev_mb_ard: "LEV_MB_ARD",
  annuity_status_pay: "ANNUITY_STATUS_PAY",
  lsoption: "LSOPTION",
  rettyp: "RETTYP",
  bs_ind: "BS_IND",
  br_ind: "BR_IND",
  ofa_indicator: "OFA_INDICATOR",
  term_mb_nrd_nsf: "TERM_MB_NRD_NSF",
  xrd_mb_term: "XRD_MB_TERM",
  xrd_surv_mb_term: "XRD_SURV_MB_TERM",
  xrd_mb_qpsa_term: "XRD_MB_QPSA_TERM",
  xrd_mb_title_iv: "XRD_MB_TITLE_IV",
  xrd_mb_4022c: "XRD_MB_4022C",
  ls_term: "LS_TERM",
  ls_qpsa: "LS_QPSA",
  pvmb_term: "PVMB_TERM",
  pvmb_title_iv: "PVMB_TITLE_IV",
  pvmb_4022c: "PVMB_4022C",
  pvf_lev_ann: "PVF_LEV_ANN",
  pvf_lev_ls: "PVF_LEV_LS",
  pvf_qpsa_ls: "PVF_QPSA_LS",
  ce_track1: "CE_TRACK1",
  ce_track2: "CE_TRACK2",
  ce_track3: "CE_TRACK3",
  ce_track4: "CE_TRACK4",
  ce_track5: "CE_TRACK5",
  ce_track6: "CE_TRACK6",
};

const BSRS_FIELDS_WITHOUT_DD_MAPPING = new Set<string>([
  "plan_id",
  "custid",
  "calculation_context",
  "role_type",
  "current_form_code",
  "current_payment_amount",
  "current_pay_status",
  "asd",
  "statement_population_indicator",
  "statement_type_code",
  "statement_status_code",
  "benefit_effective_date_for_statement",
  "display_form_code",
  "display_monthly_amount",
  "display_survivor_amount",
  "display_lump_sum_amount",
  "recalculation_trigger_indicator",
  "recalculation_reason_code",
  "suppress_statement_indicator",
  "suppression_reason_code",
  "rule_trace_id",
  "calculation_run_id",
  "deliverable_version",
  "schema_version",
  "statement_row_type",
  "statement_sort_key",
  "bsrs_configuration_output_rule_trace",
  "bsrs_configuration_output_warning_flag",
  "bsrs_configuration_output_warning_note",
]);

const INVERSE_BSRS_DD_FIELD_MAP = new Map<string, string>(
  Object.entries(BSRS_DD_FIELD_MAP).map(([fieldName, ddFieldName]) => [ddFieldName, fieldName]),
);

export function canonicalDdFieldName(bsrsFieldName: string): string {
  return BSRS_DD_FIELD_MAP[bsrsFieldName] ?? bsrsFieldName;
}

export function resolveBsrsFieldName(ddFieldName: string): string {
  return INVERSE_BSRS_DD_FIELD_MAP.get(ddFieldName) ?? ddFieldName.toLowerCase();
}

export function hasDdMapping(bsrsFieldName: string): boolean {
  return bsrsFieldName in BSRS_DD_FIELD_MAP && !BSRS_FIELDS_WITHOUT_DD_MAPPING.has(bsrsFieldName);
}
