import { createDeterministicId } from "@pbgc/shared";
import type { BenefitKernelFixture, BenefitKernelPacket } from "./types";

function booleanFromFixture(value: string): boolean {
  return value.trim().toLowerCase() === "true";
}

export function buildBenefitPacketFromFixture(fixture: BenefitKernelFixture): BenefitKernelPacket {
  const qpsa = fixture.test_case_id === "BK003";
  const qdro = false;

  return {
    packet_type: "benefit_kernel",
    schema_version: "0.1.0",
    case_id: "CASE-PLACEHOLDER",
    subject_type: "participant",
    subject_key: fixture.test_case_id,
    case_plan_timeline: {
      case_id: "CASE-PLACEHOLDER",
      plan_id: "PLAN-PLACEHOLDER",
      dopt: "2024-06-30",
      dotr: "2024-09-01",
      bpd: null,
      dobf: "2011-01-01",
    },
    resolved_plan_logic: {
      accrued_benefit_formula: fixture.accrued_benefit_formula,
      normal_single_form_rule: "sla",
      normal_married_form_rule: "qjsa_50",
      early_reduced_retirement_rule: "age_55",
      early_retirement_adjustment_rule: "4pct_per_year",
      default_actuarial_equivalence_rule: "plan_default",
      deferred_vested_normal_retirement_rule: "deferred_vested_normal",
      deferred_vested_early_retirement_rule: "deferred_vested_early",
      late_retirement_rule: "late_retirement",
      eligibility_service_rule: "plan_year_1000_hours",
      vesting_service_rule: "plan_year_1000_hours",
      benefit_service_rule: "plan_year_1000_hours",
      accrual_factor_rule: "final_average_pay_x_service",
      short_service_factor_rule: "none",
      compensation_definition_rule: "reviewed_compensation",
      average_compensation_rule: "highest_consecutive_5_years",
      covered_compensation_rule: null,
      pia_offset_rule: null,
      supplemental_benefit_rule: null,
      form_conversion_basis_rule: "plan_actuarial_equivalence",
      late_retirement_adjustment_rule: "none",
      suspension_of_benefits_rule: null,
      disability_benefit_rule: null,
      pre_retirement_death_benefit_rule: "qpsa",
      post_retirement_death_benefit_rule: null,
      vesting_schedule_rule: "reviewed_vesting",
      cash_out_rule: null,
      mandatory_employee_contribution_rule: null,
      voluntary_employee_contribution_rule: null,
      top_heavy_rule: null,
      consensual_lump_sum_rule: "not_available",
      additional_provisions_of_note: null,
    },
    participant_role_population: {
      bcv_rec_id: createDeterministicId("bcv"),
      custid: `CUST-${fixture.test_case_id}`,
      retstat: "terminated",
      id: fixture.test_case_id,
      role_type: "participant",
      fname: "Reviewed",
      lname: "Participant",
      sfname: null,
      slname: null,
      psex: "M",
      ssex: fixture.test_case_id === "BK003" ? "F" : null,
      mstat: "S",
      dob: "1960-04-15",
      sdob: null,
      dod: null,
      relation: null,
      non_spouse_benf: false,
      qdro_indicator: qdro,
      qpsa_indicator: qpsa,
      five_percent_owner_indicator: false,
      substantial_owner_indicator: false,
      retirement_status_as_of_dopt: "deferred_vested",
      payment_status_as_of_dopt: "not_in_pay",
    },
    service_employment_history: {
      doh: "1985-07-01",
      dop: "1986-01-01",
      dote: "2010-12-31",
      service_basis_code: "plan_year_1000_hours",
      service_hours_requirement: "1000",
      service_period_basis: "plan_year",
      plan_anniversary_service_basis: "anniversary",
      vesting_service_at_dopt: Number(fixture.benefit_service_resolved),
      benefit_service_at_dopt: Number(fixture.benefit_service_resolved),
      accrual_service_at_dopt: Number(fixture.benefit_service_resolved),
    },
    compensation_accrual_inputs: {
      compensation_basis_code: "final_average_pay",
      average_compensation_period: "5_year",
      compensation_history_available_indicator: true,
      final_average_compensation: Number(fixture.average_compensation_resolved),
      covered_compensation_amount: null,
      frozen_accrued_benefit_indicator: false,
      frozen_accrued_monthly_benefit: null,
      accrued_benefit_at_dopt: null,
      vested_percentage_at_dopt: 1,
    },
    benefit_administration_state: {
      dor: null,
      asd: null,
      sbcd: null,
      current_form_code: fixture.form_code_nsf === "1" ? "1" : null,
      current_payment_amount: null,
      payment_history_available_indicator: false,
      check_register_available_indicator: false,
      current_pay_status: "not_in_pay",
      elected_form_indicator: false,
      spouse_beneficiary_commencement_state: null,
    },
    actuarial_assumption_factor_set: {
      assumption_set_id: "ASSUMP-DEFAULT",
      plan_factor_table_id: "PLAN-FACTOR-DEFAULT",
      interest_basis_code: "reviewed",
      mortality_basis_code: "reviewed",
      pre_retirement_mortality_code: "reviewed",
      post_retirement_mortality_code: "reviewed",
      retirement_age_convention: "65",
      form_conversion_method: "plan_actuarial_equivalence",
      lookback_period: "5_year",
      stability_period: "1_year",
      required_beginning_date_method: "plan_default",
      lump_sum_basis_code: null,
      annuity_basis_code: "annuity_basis_default",
    },
    limitation_packet: {
      calc_indicator: true,
      calculation_context: "termination",
      section_436_applicable_indicator: booleanFromFixture(fixture.section_436_applicable_indicator),
      bankruptcy_plan_indicator: false,
      bpd_limitation_indicator: false,
      majority_owner_limitation_indicator: false,
      aggregate_limit_applicable_indicator: false,
      accrued_at_termination_limitation_indicator: false,
      phase_in_limitation_indicator: booleanFromFixture(fixture.phase_in_limitation_indicator),
      vested_at_termination_limitation_indicator: true,
      annuity_starting_date_limitation_indicator: false,
      death_benefit_limitation_indicator: false,
      form_of_benefit_limitation_indicator: false,
      actuarial_equivalence_limitation_indicator: false,
      ongoing_employment_contingency_indicator: false,
    },
    resolved_dates: {
      nrd: "2025-05-01",
      erd: "2015-05-01",
      eurd: null,
      eprd: "2015-05-01",
      rbd: "2025-05-01",
      xra: 65,
      xrd: fixture.xrd,
      sxra: 65,
      term_lw_xra: 65,
      term_lw_anb: 65,
    },
    resolved_service_compensation: {
      eligibility_service_resolved: Number(fixture.benefit_service_resolved),
      vesting_service_resolved: Number(fixture.benefit_service_resolved),
      benefit_service_resolved: Number(fixture.benefit_service_resolved),
      accrual_service_resolved: Number(fixture.benefit_service_resolved),
      compensation_resolved: Number(fixture.average_compensation_resolved),
      average_compensation_resolved: Number(fixture.average_compensation_resolved),
      covered_compensation_resolved: null,
    },
    resolved_forms_status: {
      rettyp: "deferred_vested",
      form_code_nsf: fixture.form_code_nsf === "1" ? "1" : null,
      form_code_nmf: "2",
      form_code_ptp: null,
      form_code_ptp_qpsa: qpsa ? "QPSA" : null,
      form_code_death: qpsa ? null : "QPSA",
      annuity_status_pay: "not_in_pay",
      lsoption: "N",
      bs_ind: qdro ? "QDRO" : null,
      br_ind: null,
      ofa_indicator: "N",
    },
    ...(qdro
      ? {
          qdro_packet: {
            qdro_type: "separate_interest",
            separate_interest_indicator: true,
            alternate_payee_name: "Alternate Payee",
            alternate_payee_dob: "1965-01-01",
            qdro_effective_date: "2020-01-01",
            qdro_award_description: "Reviewed separate-interest path",
          },
        }
      : {}),
    ...(qpsa
      ? {
          qpsa_packet: {
            participant_date_of_death: null,
            qpsa_eligibility_date: "2025-02-01",
            qpsa_commencement_date: "2025-05-01",
            qpsa_form_rule: "qpsa",
            qpsa_survivor_percentage: 50,
          },
        }
      : {}),
    section_436_packet: booleanFromFixture(fixture.section_436_applicable_indicator)
      ? {
          plan_year: "2025",
          aftap: "0",
          certification_date: "2025-01-01",
          aftap_doc_id: "AFTAP-PLACEHOLDER",
          presumed_aftap_rule: "reviewed",
          restriction_period_start: "2025-01-01",
          restriction_period_end: "2025-12-31",
        }
      : undefined,
    in_pay_packet: undefined,
    death_benefit_packet: undefined,
    mandatory_employee_contribution_packet: undefined,
    voluntary_employee_contribution_packet: undefined,
    disability_packet: undefined,
    asset_recovery_packet: undefined,
    cash_balance_packet: undefined,
  };
}
