const DD_FIELD_MAP: Record<string, string> = {
  case_id: "CASE",
  bcv_rec_id: "BCV_REC_ID",
  retstat: "RETSTAT",
  id: "ID",
  fname: "FNAME",
  lname: "LNAME",
  sfname: "SFNAME",
  slname: "SLNAME",
  psex: "PSEX",
  ssex: "SSEX",
  mstat: "MSTAT",
  dob: "DOB",
  sdob: "SDOB",
  dod: "DOD",
  relation: "RELATION",
  non_spouse_benf: "NON_SPOUSE_BENF",
  qdro_indicator: "QDRO_INDICATOR",
  qpsa_indicator: "QPSA_INDICATOR",
  calc_indicator: "CALC_INDICATOR",
  doh: "DOH",
  dop: "DOP",
  dote: "DOTE",
  dor: "DOR",
  sbcd: "SBCD",
  current_form_code: "FORM_CODE",
  nrd: "NRD",
  erd: "ERD",
  eurd: "EURD",
  xra: "XRA",
  xrd: "XRD",
  sxra: "SXRA",
  term_lw_xra: "TERM_LW_XRA",
  term_lw_anb: "TERM_LW_ANB",
  eligibility_service_resolved: "ESPA",
  vesting_service_resolved: "VSPA",
  benefit_service_resolved: "CSPA",
  accrual_service_resolved: "TSERV",
  compensation_resolved: "CUCOMP",
  average_compensation_resolved: "AME",
  covered_compensation_resolved: "ACOMP",
  rettyp: "RETTYP",
  form_code_nsf: "FORM_CODE_NSF",
  form_code_nmf: "FORM_CODE_NMF",
  form_code_ptp: "FORM_CODE_PTP",
  form_code_ptp_qpsa: "FORM_CODE_PTP_QPSA",
  form_code_death: "FORM_CODE_DEATH",
  annuity_status_pay: "ANNUITY_STATUS_PAY",
  lsoption: "LSOPTION",
  bs_ind: "BS_IND",
  br_ind: "BR_IND",
  ofa_indicator: "OFA_INDICATOR",
  term_mb_nrd_nsf: "TERM_MB_NRD_NSF",
  term_surv_mb_nrd: "TERM_SURV_MB_NRD",
  term_surv_mb_eurd: "TERM_SURV_MB_EURD",
  term_surv_mb_erd: "TERM_SURV_MB_ERD",
  rbd_surv_mb_term: "RBD_SURV_MB_TERM",
  term_surv_mb_ard: "TERM_SURV_MB_ARD",
  xrd_mb_term: "XRD_MB_TERM",
  xrd_surv_mb_term: "XRD_SURV_MB_TERM",
  xrd_mb_qpsa_term: "XRD_MB_QPSA_TERM",
  ls_term: "LS_TERM",
  ls_qpsa: "LS_QPSA",
  xrd_mb_title_iv: "XRD_MB_TITLE_IV",
  nrd_mb_title_iv_nsf: "NRD_MB_TITLE_IV_NSF",
  eurd_mb_title_iv_nsf: "EURD_MB_TITLE_IV_NSF",
  erd_mb_title_iv_nsf: "ERD_MB_TITLE_IV_NSF",
  rbd_mb_title_iv: "RBD_MB_TITLE_IV",
  ard_mb_title_iv: "ARD_MB_TITLE_IV",
  pvmb_title_iv_no_q_no_l: "PVMB_TITLE_IV_NO_Q_NO_L",
  pvmb_title_iv_qpsa: "PVMB_TITLE_IV_QPSA",
  pvmb_title_iv_no_load: "PVMB_TITLE_IV_NO_LOAD",
  title_iv_load: "TITLE_IV_LOAD",
  pvmb_title_iv: "PVMB_TITLE_IV",
  xrd_mb_4022c: "XRD_MB_4022C",
  pvmb_4022c_no_q_no_l: "PVMB_4022C_NO_Q_NO_L",
  pvmb_4022c_qpsa: "PVMB_4022C_QPSA",
  pvmb_4022c_no_load: "PVMB_4022C_NO_LOAD",
  load_4022c: "LOAD_4022C",
  pvmb_4022c: "PVMB_4022C",
  pvmb_bas_ungb_no_q_no_l: "PVMB_BAS_UNGB_NO_Q_NO_L",
  pvmb_bas_ungb_qpsa: "PVMB_BAS_UNGB_QPSA",
  bnnfa_pvmb_no_load: "BNNFA_PVMB_NO_LOAD",
  bnnfa_load: "BNNFA_LOAD",
  bnnfa_pvmb: "BNNFA_PVMB",
  pvpbl_ann_rates_no_q_no_l: "PVPBL_ANN_RATES_NO_Q_NO_L",
  pvpbl_ann_rates_qpsa: "PVPBL_ANN_RATES_QPSA",
  pvpbl_ann_rates_no_load: "PVPBL_ANN_RATES_NO_LOAD",
  pbl_load: "PBL_LOAD",
  pvpbl_ann_rates: "PVPBL_ANN_RATES",
  pvf_lev_ann: "PVF_LEV_ANN",
  pvf_lev_ls: "PVF_LEV_LS",
  pvf_qpsa_ls: "PVF_QPSA_LS",
  pvmb_term_no_q_no_l: "PVMB_TERM_NO_Q_NO_L",
  pvmb_term_qpsa: "PVMB_TERM_QPSA",
  pvmb_term_no_load: "PVMB_TERM_NO_LOAD",
  term_load: "TERM_LOAD",
  pvmb_term: "PVMB_TERM",
};

const NO_DD_MAPPING_FIELDS = new Set<string>([
  "plan_id",
  "listing_row_type",
  "listing_sort_key",
  "role_type",
  "custid",
  "current_payment_amount",
  "current_pay_status",
  "elected_form_indicator",
  "spouse_beneficiary_commencement_state",
  "calculation_context",
  "valuation_listings_output_rule_trace",
  "valuation_listings_output_warning_flag",
  "valuation_listings_output_warning_note",
]);

const INVERSE_DD_FIELD_MAP = new Map<string, string>(
  Object.entries(DD_FIELD_MAP).map(([outputField, ddField]) => [ddField, outputField]),
);

export function canonicalDdFieldName(outputFieldName: string): string {
  return DD_FIELD_MAP[outputFieldName] ?? outputFieldName.toUpperCase();
}

export function resolveValuationFieldName(ddFieldName: string): string {
  return INVERSE_DD_FIELD_MAP.get(ddFieldName) ?? ddFieldName.toLowerCase();
}

export function hasDdMapping(outputFieldName: string): boolean {
  return !NO_DD_MAPPING_FIELDS.has(outputFieldName) && outputFieldName in DD_FIELD_MAP;
}
